### ISSUE TITLE
Regisztráció és beléptetés

### ISSUE THREAD

**Issue by ghost** [Pepita73/webproghu_dev#33]
A regisztráció megvalósítását lehet lekövetni itt.

- [ ] - #24 - captcha modul választás
- [ ] - #21 - password_hash modul a default Drupal hash megoldás felülírására
- [ ] - captcha berakása a jelszavas regisztrációhoz
- [ ] - github auth modul, [all around check](https://www.drupal.org/project/social_login)
- [ ] - github regisztrációs form + adatvédelmi nyilatkozat (helye legyen, szöveg utólag)
- [ ] - github login.
- [ ] - egy GDPR - tájékoztató című issue-ba felvenni tételesen a megadandó és megadható adatokat
